require("nukevim.mappings.core_nukevim_mapping")
require("nukevim.mappings.telescope_mapping")
require("nukevim.mappings.neo_tree_mapping")
require("nukevim.mappings.nvim-lspconfig")
require("nukevim.mappings.none-ls")
